### PR TITLE
Fix `getOptions` support for Windows machines

### PR DESCRIPTION
**Pull request by mastrzyz**
Solves issue -> https://github.com/jest-community/jest-junit/issues/107

Current `getOptions` goes up the directory tree until we hit `path.sep` , aka "/".

This works on Nix based platforms but on windows we hit an infinite loop at `path.dirname("C:\\")` , since we can't go to "/" from "C:\\".

Instead we should be leveraging `path.parse` which actually tells us the root directory of a path.

Added the incomplete UT for this as well as a try/catch around the require statement since it can also fail if the import isn't working like through bundling via webpack.

### CODE REVIEW

**Comment by palmerj3** [comment]
Sorry for the delay.

Thank you!!

This looks pretty great to me and I'm happy to merge. I just need to ask that you remove the version bump in package.json first. I do the version bumping when cutting a new release.

So once you do that I'll merge this and the other PR of yours and cut a release.

**Comment by mastrzyz** [comment]
Done! @palmerj3

**Comment by mastrzyz** [comment]
@palmerj3 ?

**Comment by palmerj3** [comment]
Hey @mastrzyz sorry for the delay. Just started a new job this week.

I'll carve out some time this weekend to get these things merged and published.

**Comment by mastrzyz** [comment]
@palmerj3  any luck with merging

**Comment by mastrzyz** [comment]
Hey @palmerj3  is there anyone else I can ping here for review?

**Review by palmerj3 — APPROVED** [review]

**Comment by palmerj3** [comment]
Sorry for the delay. I merged both your PRs and published version 14.0.0 with the changes.

Thanks again!

**Pull request merged**
