### PR TITLE
Added {suitename} as possible injection value for classNameTemplate

### PR DESCRIPTION
**Pull request by dtom90**
Allows the user to create a `classNameTemplate` which contains `{suitename}`

This was the main case I was looking for, but could also be done for `suiteNameTemplate` and `titleNameTemplate` if it seems helpful.

Also added a few tests for `classNameTemplate` and corrected a link in `index.js`

### CODE REVIEW

**Comment by palmerj3** [comment]
Sweet! Looks good to me.

I'll push a new release this weekend.

**Comment by dtom90** [comment]
Awesome, thanks!

**Comment by palmerj3** [comment]
This is now published as part of 11.1.0.

Thanks!

**Comment by dtom90** [comment]
All working in our build environment. Thanks again for the quick merge & release!

**Pull request merged**
