### PR TITLE
Add support for test suite properties. Upgrade mkdirp. Drop node < 10 support

### PR DESCRIPTION
**Pull request by palmerj3**
This PR addresses the mkdirp security vulnerability by upgrading to the latest version.
This also drops node < 10 support for jest-junit.
As of Jest v26.0.0 jest itself no longer supports node < 10.

This PR also adds the ability to define custom test suite properties.

### CODE REVIEW

**Comment by karfau** [comment]
Can you help me to understand if there is anything specific in jest 25 that will stop working with jest-junit?
Because in our project the CI build works fine with the latest version if jest-junit even though jest is still at v25.

**Comment by palmerj3** [comment]
No it should work just fine with older versions of jest, even far below 25.

But older versions of jest used to support node 8. So really this recent change just updates node.js support.

**Comment by karfau** [comment]
So you could basically still test against node 10 and jest v25 but decided to not do that?

**Comment by palmerj3** [comment]
My thought process when maintaining jest-junit this entire time has been to share the same runtime requirements as jest.

But you're making me think that I should at least test for earlier versions of jest in CI.
If there is some breaking change in the future I would stick to my first sentence.

But right now I see no reason the latest jest-junit wouldn't work in several older jest versions.
I'll push a change now to add the last two or three jest versions to the CI build.

**Comment by palmerj3** [comment]
Ok I've re-added CI testing for node >= 10 and jest >= 22.0.0. So for the time being we know 11.0.0 has support for this and I'll do my best to keep it that way.

Thanks for commenting!

**Comment by karfau** [comment]
Thank you for reconsidering, it provides confidence.

**Pull request merged**
