### PR TITLE
fix: upgrade Jest

### PR DESCRIPTION
**Pull request by SimenB**

### CODE REVIEW

**Comment by SimenB** [comment]
I made this change on GitHub. This repo doesn't seem to have a lockfile, though

**Comment by palmerj3** [comment]
@SimenB I can take a look further at this. Can probably remove the jest 22 check at this point if that's breaking things.

Is this urgent or needed for a release?

**Comment by SimenB** [comment]
Nah, just noisy in lockfiles after upgrading since jest-config pulls in babel-cora@6

**Comment by siemiatj** [comment]
+1 . I had to disable junit for now as it's sucking in babel-core 6.x :/

**Comment by SimenB** [comment]
#81

**Pull request closed without merging**
