### PR TITLE
todo test added to report

### PR DESCRIPTION
**Pull request by aakilli**

### CODE REVIEW

**Comment by palmerj3** [comment]
Hello!

So "todos" is not a valid property of the testsuite attribute. You can see that here:
https://github.com/jest-community/jest-junit/blob/master/__tests__/lib/junit.xsd#L73

So if we were to merge this it could cause some breakages in users CI environments.

Given that todo's are someone close to skipped tests, in that both are not run, I would be fine incrementing the number of skipped tests.

But we cannot make a junit file that distinctly classifies todo tests because it would result in a non-standard junit file and could break in CI environments.

**Comment by aakilli** [comment]
Hello!

I have removed "todos" property and incremented skipped test count.

**Comment by palmerj3** [comment]
The most recent change looked good to me. Are you resubmitting?

**Comment by aakilli** [comment]
Yes, I will resubmit them next week.

**Comment by palmerj3** [comment]
Please push a commit as our CI has changed

**Pull request closed without merging**
