### PR TITLE
Add file attr if JEST_JUNIT_ADD_FILE_ATTRIBUTE is true

### PR DESCRIPTION
**Pull request by mtsmfm**
ref: https://github.com/jest-community/jest-junit/pull/71#issuecomment-453543810

### CODE REVIEW

**Comment by palmerj3** [comment]
Sweet!

Code looks good. Would you mind just doing two additional things?

I'd like you to link to any documentation in circle-ci in the README so folks know this file attribute is primarily for there. If that doesn't exist then perhaps just expand on the README description of the setting a bit, mentioning that it provides richer details for circle-ci but may break on other CI platforms if enabled.

The other bit I'd like you to do is add another test which tests that the file attribute does not exist without the setting.

Thank you!!

**Comment by mtsmfm** [comment]
@palmerj3 

> I'd like you to link to any documentation in circle-ci in the README

I can't find any doc about `file` attr.
I think https://circleci.com/docs/2.0/collect-test-data/ is the most similar one.

I've added a description and test.

**Comment by palmerj3** [comment]
@nicolasschabram would you be willing to test out this PR on your jenkins configuration to see if it breaks?

By default it should be just fine - but will break your setup if the JEST_JUNIT_ADD_FILE_ATTRIBUTE exists.

**Comment by nicolasschabram** [comment]
Yup,  seems to work. Jenkins fails with the same error I had in https://github.com/jest-community/jest-junit/issues/74 when setting this in package.json:

```json
"jest-junit": {
  "addFileAttribute": "true"
}
```

Without it, everything works fine.

(Btw, I noticed it only picks up the setting with `"true"` but not with `true`.)

Anyway, thanks a lot for the fix!

**Comment by mtsmfm** [comment]
> (Btw, I noticed it only picks up the setting with `"true"` but not with `true`.)

I used `usePathForSuiteName` as a reference:

```
Or you can also define a jest-junit key in your package.json. All are string values.

{
  ...
  "jest-junit": {
    "suiteName": "jest tests",
    "outputDirectory": ".",
    "outputName": "./junit.xml",
    "classNameTemplate": "{classname}-{title}",
    "titleTemplate": "{classname}-{title}",
    "ancestorSeparator": " › ",
    "usePathForSuiteName": "true"
  }
}
```

**Comment by mtsmfm** [comment]
@palmerj3 Is there any blocker to merge this PR?

**Comment by palmerj3** [comment]
@mtsmfm hey I don't think so. I'm going to go ahead and merge it and push a new version.

**Comment by palmerj3** [comment]
@mtsmfm v6.3.0 was published with this change

**Pull request merged**
