### PR TITLE
Replace <rootDir> prior to path.join()

### PR DESCRIPTION
**Pull request by arabull**
This allows outputDirectory to be formatted like `<rootDir>/../some/dir`. In that case, `path.join()` assumes the `..` cancels out the `<rootDir>`, which seems entirely reasonable. Unfortunately, it means the final value is `some/dir`, and that ends up rooted at `process.cwd()`, which doesn't always match `<rootDir>`.

Handling the `<rootDir>` replacement first alleviates this problem.

### CODE REVIEW

**Comment by arabull** [comment]
Wasn't sure if I need to manually bump the version or not. Let me know if I should do that, and I can.

**Comment by arabull** [comment]
Fixes jest-community/jest-junit#153.

**Comment by palmerj3** [comment]
Thank you! Please add a test so we know if this behavior regresses in future releases.

**Comment by arabull** [comment]
I was looking for a place to add a test, but there weren't any tests against `index.js` or `processor`, which is where the fix lives.

The `processor` function ends up writing a file, which we probably don't want a test to do. To properly test the logic I changed, I may have to refactor `processor`. That felt excessive to me, but I can do it if you'd prefer. Or I'm open to other suggestions.

**Comment by palmerj3** [comment]
Ok hold off for now. I'll take a closer look at this PR and the testability of things later on.

**Comment by arabull** [comment]
@palmerj3 Anything I can do to help get this merged? I'm happy to refactor the `processor` function to make it more testable if you'd like. It just felt a little dangerous for this small change.

**Review by palmerj3 — APPROVED** [review]

**Comment by arabull** [comment]
@palmerj3 Done. I had to re-apply my changes in a new location due to https://github.com/jest-community/jest-junit/pull/168. Let me know if I screwed anything up.

**Comment by palmerj3** [comment]
This has been released in 13.0.0

**Pull request merged**
