### PR TITLE
[feat] Add addFileAttributePathPrefix attribute

### PR DESCRIPTION
**Pull request by adrian-mezei**
It would be nice to have path prefixing possible for addFileAttribute. If the tested files are not in the root directory of the repository, than GitLab or other ci/cd tools are not able to find them.

### CODE REVIEW

**Comment by adrian-mezei** [comment]
Hi @palmerj3, can you have a look at this PR sometimes?

**Comment by palmerj3** [comment]
@adrian-mezei Thanks for submitting! Can you expand on why this change is necessary? I'm not understanding your initial description, sorry.

I'm assuming that in your CI environment jest's root is not the same as the CI root and so you'd like to set a junit.xml path of something like ../.../junit.xml?

Also before I can consider merging this I'd like you to add a test or two in __tests__/buildJsonResults.test.js - you'll see the format most follow when writing a test that confirms the behavior of settings and/or combinations of settings.

**Comment by palmerj3** [comment]
Yes the generated junit file file paths are going to be based on jests root and that makes perfect sense.

But it seems to me that you have a solution which can move the generated junit.xml file to another directory. So I don't see a need for a third property that does the same thing.

**Comment by palmerj3** [comment]
If there is a bug in how outputDirectory and outputFile work for your situation then filing an issue with steps to reproduce & sample repo or generating a pull request to fix would be much appreciated. Closing this for now.

**Comment by palmerj3** [comment]
I think that this particular functionality best belongs outside of the reporter.

Here is a relevant thread in jest itself along with a possible fix for your situation.

https://github.com/facebook/jest/issues/3613

**Pull request closed without merging**
