### PR TITLE
Add filePathPrefix option

### LINKED ISSUE #202: Add "fileTemplate" to complement "addFileAttribute"
In a monorepo, the package is not at the root of git repository. 

Meaning, `addFileAttribute` becomes inaccurate.

Please add `fileTemplate` so that we can use like:

```
fileTemplate: 'packages/qc-api/{filepath}',
```

which will be correct path relative to repository root.

### PR DESCRIPTION
**Pull request by marvinroger**
Fix #202

### CODE REVIEW

**Comment by palmerj3** [comment]
Looks good to me. Thank you!

**Comment by marvinroger** [comment]
Thank you for your reactivity!

**Comment by palmerj3** [comment]
This has been published to 13.2.0.

Thanks again!

https://github.com/jest-community/jest-junit/releases/tag/v13.2.0

**Comment by ceefour** [comment]
Thanks much @marvinroger @palmerj3

**Pull request merged**
