### PR TITLE
feature: support function as config for title,classname and suitename

### LINKED ISSUE #54: Support mapping function to classNameTemplate
When using junit report with java the classname contains the package name and the class name.
Tools like Jenkins CI assume this format and group test result by package name by using everything before the last `.` in the classname as a package name.

When using junit-jest it would be useful to support mapping the file folder to the "package" name but `/` would need to be replaced by `.`.

This is currently not possible with the templates as string but could be achieved if the classNameTemplate would accept a javascript function taking as arguments an object with a poperty for each variables accepted by templates ( {classname}, {title}, {filepath}, {filename}, {displayName}) and return a string

the jestconfig could then look something like 
```javascript
module.exports = {
   ...baseConfig,
   "reporters": [
      ["jest-junit", {
         classNameTemplate: function (variables) {
            const folder = variables.filepath.substr(0, variables.filepath.length - variables.filename.length)
            return folder.replace(/\//g, '.');
         }
      }]
   ]
};
```
It could also be nice to have an additional `filefolder` variable to avoid doing substrings in the function.

Thanks for the project!

### PR DESCRIPTION
**Pull request by sarod**
Fixes #54

### CODE REVIEW

**Comment by palmerj3** [comment]
@sarod excellent work! Thanks so much for taking the time to submit an issue and a PR!

My one and only concern with this is that this would be the first deviation in configurability - it's a feature currently only usable if you use the reporter config. I'm actually ok with that if you can foresee that others would have vastly different needs for specifying class name.

The alternative would be to add an additional configuration option that would hardcode this behavior. For instance, having a configuration option called javaJunitClassname: true and it would do as you describe in the issue.

What do you think? I'm fine merging this if you can think of more use-cases that require a function.

Thanks!

**Comment by sarod** [comment]
Hi @palmerj3,

I understand you concern.
 
In my case what I actually do with the function is:
* remove a common (src/) prefix from the filepath 
* remove the ".test.ts" extension from the file name.
* convert potential other . in the filename to _

Here is the function I'm actually using to compute classname:
```
classNameTemplate: ({filepath, filename, classname}) => {
   let folder = filepath.substring(0, filepath.length - filename.length);
   if (folder.startsWith('/src')) {
      folder = folder.substring('/src'.length);
   }
   const folderWithDots = folder.replace(/\//g, '.');
   const fileWithoutExtensionOrDots = filename
      .replace(/(\.(spec|test))?\.ts(x)?/, '')
      .replace(/\./g, '_');
   return folderWithDots + fileWithoutExtensionOrDots;
}
```
We could probably add string and flags properties to support this case but I feel like at some point it would be more cumbersome to try to find the right combination of flags rather than writing a function with a few lines of codes. 

So I think supporting functions allows for much more flexibility while keeping the number of configuration options in the project reasonable.

**Comment by palmerj3** [comment]
Ok makes sense

**Comment by palmerj3** [comment]
I'll publish a release later today

**Comment by sarod** [comment]
Excellent. Thanks!

**Comment by palmerj3** [comment]
@sarod 5.1.0 was just published containing this feature.

Thanks again! Excellent work.

**Comment by palmerj3** [comment]
https://github.com/jest-community/jest-junit/releases/tag/v5.1.0

**Pull request merged**
