### PR TITLE
Add XML prolog to junit output

### PR DESCRIPTION
**Pull request by lalugeo**
### Issue: 
Many XML parsers require the XML Prolog at the beginning of the xml file to start parsing. 

### Change proposed
~~Add an optional feature to control whether the generated XML should contain a XML prolog or not.This is controlled with the newly created flag called `includeXmlProlog`  as the package.json key or `JEST_JUNIT_INCLUDE_XML_PROLOG` as the environment variable.~~
Include the declaration of the XML prolog persistently in the output always

### Before
```xml
<testsuites name="jest tests">
  <testsuite name="addition" tests="1" errors="0" failures="0" skipped="0" timestamp="2017-07-13T09:42:28" time="0.161">
    <testcase classname="ADDITION POSITIVE NUMBERS" name="addition positive numbers should add up" time="0.004">
    </testcase>
  </testsuite>
</testsuites>
```

### After
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="jest tests">
  <testsuite name="addition" tests="1" errors="0" failures="0" skipped="0" timestamp="2017-07-13T09:42:28" time="0.161">
    <testcase classname="ADDITION POSITIVE NUMBERS" name="addition positive numbers should add up" time="0.004">
    </testcase>
  </testsuite>
</testsuites>
```

### CODE REVIEW

**Comment by palmerj3** [comment]
Hey @lalugeo thanks for submitting this!

Can you just briefly describe what this PR achieves? Are you having an issue with the generated XML?

**Comment by lalugeo** [comment]
> Hey @lalugeo thanks for submitting this!
> 
> Can you just briefly describe what this PR achieves? Are you having an issue with the generated XML?

Thank you for the quick response. But sorry, i was just editing the PR :)

**Comment by palmerj3** [comment]
@lalugeo ok that seems reasonable. Given this do you see any risk in this simply being hardcoded and not a CLI option?

So we would always have a prolog.

**Comment by lalugeo** [comment]
The risk might be to any text based or regex based parsing being done by the consumers of this package on the output xml file. In such scenarios, this PR would break their implementations. Hence I added a flag that has default value of false, causing the prolog to be not added to the output. So if any consumer of this package, needs the prolog, they have to specifically turn on this flag. 

But of course, to keep it simple, we could always harcode it without any of the options, which would cause the prolog to be returned always.

**Comment by palmerj3** [comment]
I'm not too worried about people who parse these with regex when we generate valid xml.

If you wouldn't mind, I think I would rather see this prolog hard coded so we reduce the configuration options.

**Comment by lalugeo** [comment]
Sure, i have made those changes.

**Comment by lalugeo** [comment]
Yes, you are right, this is a way more cleaner option. Thanks for pointing me out in that direction.

**Comment by lalugeo** [comment]
@palmerj3 , any updates on the merge?

**Comment by palmerj3** [comment]
@lalugeo hey I'm sorry I've been quite busy this week. I will get to this tomorrow.

**Comment by palmerj3** [comment]
@lalugeo this has been merged and I published jest-junit 6.1.0 which includes this. Please let me know if there are any issues.

**Pull request merged**
